default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "127.0.0.1") %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'password') %>
  port: <%= ENV['DATABASE_PORT']%>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'dev_project_management') %>

test:
  <<: *default
  database: <%= ENV.fetch('TEST_DATABASE_NAME', 'test_project_management') %>
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
