default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'password' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'dev_project_management' %>

test:
  <<: *default
  database: test_project_management

production:
  url: <%= ENV['DATABASE_URL'] %>
