name: RSpec Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: test_project_management
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.2"
          bundler-cache: true

      - name: Database setup
        run: |
          cd backend
          bundle config set --local deployment 'true'
          bundle install
          RAILS_ENV=test bundle exec rails db:prepare

      - name: Run RSpec
        run: |
          cd backend
          RAILS_ENV=test bundle exec rspec
