name: RSpec Tests

on: [push, pull_request]

defaults:
  run:
    working-directory: backend

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/test_project_management

    services:
      postgres:
        image: postgres:16
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: test_project_management
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.2"
          bundler-cache: true
          working-directory: backend

      - name: Database setup
        run: bundle exec rails db:prepare

      - name: Run RSpec
        run: bundle exec rspec

      - name: Deploy to Railway
        if: github.ref == 'refs/heads/main'
        run: |
          npm install -g @railway/cli
          echo "--- 現在のディレクトリ一覧 ---"
          ls -F
          echo "----------------------------"
          railway up --service "backend" --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
